handlers= java.util.logging.FileHandler, java.util.logging.ConsoleHandler
.level=FINEST


java.util.logging.FileHandler.pattern = log/log%g.txt
java.util.logging.FileHandler.limit = 1000000
java.util.logging.FileHandler.count = 5
java.util.logging.FileHandler.level = FINER

java.util.logging.FileHandler.maxLocks = 100
java.util.logging.FileHandler.formatter = com.github.rob269.helloMessengerServer.logging.LogFormatter


java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = com.github.rob269.helloMessengerServer.logging.LogFormatter
